<?php	
	require_once("mvc/library/phptal/PHPTAL.php");	
	require_once("mvc/library/tcpdf/tcpdf.php");
	require_once("mvc/library/Number.php");
	require_once("mvc/library/Date.php");
	require_once("mvc/library/Mail.php");
	require_once("mvc/library/Captcha.php");
	require_once("mvc/library/Encrypted.php");	
	require_once("mvc/library/UploadImage.php");
	require_once("mvc/library/Image.php");
	require_once("mvc/library/String.php");
	require_once("mvc/library/Statistic.php");
	require_once("mvc/library/SimpleHtmlDom.php");
?>