<?php 
function tpl_4f8265f1_login__taZDoI3qADB_iRl25TMgmg(PHPTAL $tpl, PHPTAL_Context $ctx) {
$_thistpl = $tpl ;
$_translator = $tpl->getTranslator() ;
/* tag "documentElement" from line 1 */ ;
$ctx->setDocType('<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">',false) ;
?>

<?php /* tag "html" from line 2 */; ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<?php /* tag "head" from line 3 */; ?>
<head>
	<?php /* tag "meta" from line 4 */; ?>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<?php /* tag "title" from line 5 */; ?>
<title>Sim số đẹp giá rẻ</title>
	<?php /* tag "link" from line 6 */; ?>
<link rel="stylesheet" type="text/css" href="../Template/css/main2.css"/>
	<?php /* tag "link" from line 7 */; ?>
<link rel="stylesheet" type="text/css" href="../Template/css/datatable.css"/>
	<?php /* tag "link" from line 8 */; ?>
<link rel="stylesheet" type="text/css" href="../Template/css/jquery-ui-1.8.11.custom.css"/>
	
	<?php /* tag "script" from line 10 */; ?>
<script type="text/javascript" language="javascript" src="../Template/script/jquery.js"></script>
	<?php /* tag "script" from line 11 */; ?>
<script type="text/javascript" language="javascript" src="../Template/script/jquery.dataTables.js"></script>	
	<?php /* tag "script" from line 12 */; ?>
<script type="text/javascript" language="javascript" src="../Template/script/jquery.init.dataTables.js"></script>	
</head>
<?php /* tag "body" from line 14 */; ?>
<body>
	<?php /* tag "div" from line 15 */; ?>
<div id="frame">
		<?php /* tag "div" from line 16 */; ?>
<div id="header"></div>
			<?php 
/* tag "span" from line 17 */ ;
$ctx->pushSlots() ;
$tpl->_executeMacroOfTemplate('macros.xhtml/MenuIndex', $_thistpl) ;
$ctx->popSlots() ;
?>

		<?php /* tag "div" from line 18 */; ?>
<div id="main">
			<?php /* tag "div" from line 19 */; ?>
<div id="main3_of1">
				<?php 
/* tag "span" from line 20 */ ;
$ctx->pushSlots() ;
$tpl->_executeMacroOfTemplate('macros.xhtml/Main3of1', $_thistpl) ;
$ctx->popSlots() ;
?>

			</div>
			<?php /* tag "div" from line 22 */; ?>
<div id="main3_of2_height">				
				<?php /* tag "div" from line 23 */; ?>
<div id="tieude_main">Thông tin đăng nhập</div>
					<?php /* tag "table" from line 24 */; ?>
<table width="100%" border="0" align="center" cellspacing="0" cellpadding="0">
						<?php /* tag "form" from line 25 */; ?>
<form method="post" action="login.php">							
								<?php /* tag "tr" from line 26 */; ?>
<tr height="30px"><?php /* tag "td" from line 26 */; ?>
<td width="200" align="right" class="DK">Họ Tên:</td>
									<?php /* tag "td" from line 27 */; ?>
<td align="left"> <?php /* tag "input" from line 27 */; ?>
<input class="input text" type="text" size="40" name="user_"/></td>
								</tr>
								<?php /* tag "tr" from line 29 */; ?>
<tr height="30px"><?php /* tag "td" from line 29 */; ?>
<td width="200" align="right" class="DK">Mật Khẩu:</td>
									<?php /* tag "td" from line 30 */; ?>
<td align="left"> <?php /* tag "input" from line 30 */; ?>
<input class="input text" type="password" size="40" name="name_"/></td>
								</tr>
								<?php /* tag "tr" from line 32 */; ?>
<tr align="center">
									<?php /* tag "td" from line 33 */; ?>
<td colspan="2" height="50px"><?php /* tag "input" from line 33 */; ?>
<input type="submit" value="Đăng Nhập"/></td>
								</tr>
						</form>	
					</table>  
			</div>
			<?php /* tag "div" from line 38 */; ?>
<div id="main3_of3">
				<?php 
/* tag "span" from line 39 */ ;
$ctx->pushSlots() ;
$tpl->_executeMacroOfTemplate('macros.xhtml/Main3of3', $_thistpl) ;
$ctx->popSlots() ;
?>
 
				<?php /* tag "div" from line 40 */; ?>
<div style="border: 1px solid #999; height: 242px;">
					<?php /* tag "a" from line 41 */; ?>
<a href="http://tkpc.vn/" target="_blank"><?php /* tag "img" from line 41 */; ?>
<img width="100%" height="50%" border="0" src="../Template/images/tinkhoa.gif" alt="Quang Cao"/></a><?php /* tag "br" from line 41 */; ?>
<br/>
					<?php /* tag "a" from line 42 */; ?>
<a href="http://sncpc.com/home/" target="_blank"><?php /* tag "img" from line 42 */; ?>
<img width="100%" height="50%" border="0" src="../Template/images/snc.gif" alt="Quang Cao"/></a><?php /* tag "br" from line 42 */; ?>
<br/>
				</div>
			</div>
			<?php /* tag "div" from line 45 */; ?>
<div class="vide"></div>
		</div>
		<?php /* tag "div" from line 47 */; ?>
<div id="line"></div>
		<?php 
/* tag "div" from line 48 */ ;
$ctx->pushSlots() ;
$tpl->_executeMacroOfTemplate('macros.xhtml/Footer', $_thistpl) ;
$ctx->popSlots() ;
?>

		<?php /* tag "div" from line 49 */; ?>
<div class="vide"></div>
	</div>
</body>
</html><?php 
/* end */ ;

}

?>
<?php /* 
*** DO NOT EDIT THIS FILE ***

Generated by PHPTAL from D:\AppWebServer\SimShopping\hai_sim24h\Template\login.html (edit that file instead) */; ?>