<?php	
	require_once("mvc/library/phptal/PHPTAL.php");
	require_once("mvc/library/tcpdf/tcpdf.php");
	require_once("mvc/library/Number.php");
	require_once("mvc/library/Date.php");
	require_once("mvc/library/Mail.php");	
	require_once("mvc/library/CartShopping.php");	
	require_once("mvc/library/Captcha.php");	
?>